campground:
  name: "Saranac Lake Islands"
  contract_code: "NY"
  park_id: 562
  base_url: "https://newyorkstateparks.reserveamerica.com"

search:
  min_consecutive_nights: 4
  date_ranges:
    - label: "July A"
      start: "2025-07-22"
      end: "2025-07-27"
      active: true

    - label: "July B"
      start: "2025-07-29"
      end: "2025-08-03"
      active: true

sites:
  # mode options:
  #   "any"            — alert on every available site
  #   "preferred_list" — alert on all sites, but flag preferred ones
  #   "specific_only"  — only alert on sites in preferred/watch lists
  mode: "preferred_list"

  preferred:
    - id: 3
    - id: 4
    - id: 5
    - id: 13
    - id: 35
    - id: 21
    - id: 22
    - id: 23
    - id: 24
    - id: 27
    - id: 28
    - id: 19
    - id: 20
    - id: 74

  watch: []
